name = "ScatteringInterpretation"
uuid = "2e72716b-aab1-426f-8785-52471c319e22"
authors = ["dsweber2 <david.weber2@protonmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
